### ISSUE TITLE
New to C++, struggling to build SDK

### ISSUE THREAD

**Issue by oofsamy** [Youda008/OpenRGB-cppSDK#2]
Hey, I'm following the instructions on the `readme.md`, I've cloned the git repo in the command line like so `git clone https://github.com/Youda008/OpenRGB-cppSDK.git`, `cd OpenRGB-cppSDK`, `git submodule update --init`, `mkdir build-release`, `cd build-release` and `cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ../`. This is what is logged in the command line but I'm not sure what else to include.

![image](https://user-images.githubusercontent.com/61066276/149180160-5951b063-c295-49e2-ab28-00d686cca52c.png)

And afterwards in the `build-release` folder, no sort off `.lib` `.dll` or anything is generated, just a bunch of cache files to my eyes.

**Comment by Youda008** [comment]
There is no error in the screenshot, the build files have been successfully generated.
Now it should be possible to open the *.vcxproj in Visual Studio and build it there in the UI.
But i don't use Visual Studio, so i'm not completely sure.

**Comment by oofsamy** [comment]
Is someone able to build this library for me, been trying for a day and always get these random errors. 
![image](https://user-images.githubusercontent.com/61066276/149417346-2fac05eb-e1f7-4896-b7d1-d8db4a16d834.png)

**Comment by Youda008** [comment]
I will try to build it on my company laptop, where i have Visual Studio installed.

**Comment by Youda008** [comment]
Sorry, these errors are not your fault. I wrote some includes in a way that was incompatible with Visual Studio compiler and library. I fixed that now. Can you please try again? Write
```
git pull origin master
git submodule update
```
then open `OpenRGB_cppSDK.sln` and compile.

**Comment by oofsamy** [comment]
Ayyy finally got the .lib compiled, tysm for the fix!

**Comment by oofsamy** [comment]
Nevermind a new issue, I can never solve linker errors, I have the `orgbsdk.lib` library added and added the include files, any chance you know what this could be?
![image](https://user-images.githubusercontent.com/61066276/149619285-900289d0-52ec-4bc7-9bb0-3d97ec604460.png)

**Comment by Youda008** [comment]
Yes, you need to link library `ws2_32`, that's a standard Windows socket library for networking.

**Comment by oofsamy** [comment]
Thanks for the help, got it all working now!
